# Generated by Django 4.0.3 on 2022-04-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbook',
            old_name='authr',
            new_name='author',
        ),
    ]
